const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generates an Inquiry PDF Report and returns the buffer.
 * @param {Object} inquiryData - The form data submitted by the user.
 * @returns {Promise<Buffer>} - The generated PDF as a buffer (to attach to email).
 */
const generateInquiryPDF = (inquiryData) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50 });
            let buffers = [];

            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => {
                const pdfData = Buffer.concat(buffers);
                resolve(pdfData);
            });

            // --- Header ---
            // --- Header ---
            // --- Header ---
            // Logo Image
            const logoPath = path.join(__dirname, '../assets/ASK-logo.png');
            if (fs.existsSync(logoPath)) {
                // Buffer reading sometimes helps with pdfkit static assets
                doc.image(logoPath, 50, 40, { width: 150 });
            }

            // Title Adjustment: Brought upper (Y=70) and Centered - ABOVE the line
            doc.y = 70;
            doc.fillColor('#0f172a')
                .fontSize(18)
                .font('Helvetica-Bold')
                .text('Inquiry Details', { align: 'center' });

            doc.moveDown();
            // Ensure the line below header is low enough to not overlap image
            doc.moveTo(50, 110).lineTo(550, 110).strokeColor('#e2e8f0').stroke();

            // --- Body Start ---
            doc.y = 115; // Set cursor below the line

            // --- Inquiry Details Table-like layout ---
            const startX = 50;
            let currentY = doc.y + 20;
            const labelWidth = 150;

            const addField = (label, value) => {
                doc.fillColor('#64748b').fontSize(11).font('Helvetica-Bold').text(label, startX, currentY);
                doc.fillColor('#334155').fontSize(11).font('Helvetica').text(value || 'N/A', startX + labelWidth, currentY, { width: 350 });
                currentY = doc.y + 15; // Move down
            };

            const formatDate = (dateString, isNotConfirmed) => {
                if (isNotConfirmed) return "Not Confirmed Yet";
                if (!dateString) return "N/A";
                return new Date(dateString).toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' });
            };

            addField('Inquiry ID:', inquiryData._id ? inquiryData._id.toString() : 'New');
            addField('Submission Date:', new Date().toLocaleString());
            doc.moveDown();
            currentY += 10;

            doc.font('Helvetica-Bold').fontSize(14).fillColor('#0e3a6c').text('Travel Details', startX, currentY);
            currentY += 25;

            addField('Guest Name:', inquiryData.name);
            addField('Destination / Note:', inquiryData.note);
            currentY += 10; // Extra spacing for potentially long note
            addField('Arrival Date:', formatDate(inquiryData.arrivalDate, inquiryData.isDateNotConfirmed));

            const travelerStr = `${inquiryData.travelers?.adults || 0} Adults, ${inquiryData.travelers?.children || 0} Kids, ${inquiryData.travelers?.toddlers || 0} Toddlers`;
            addField('Travelers:', travelerStr);

            doc.moveDown();
            currentY += 20;

            doc.font('Helvetica-Bold').fontSize(14).fillColor('#0e3a6c').text('Contact Information', startX, currentY);
            currentY += 25;

            addField('Preference:', inquiryData.connectOnWhatsapp ? 'Contact via WhatsApp' : 'Contact via Email');
            if (inquiryData.connectOnWhatsapp) {
                addField('WhatsApp Number:', inquiryData.whatsappNumber);
            }
            if (inquiryData.email) {
                addField('Email Address:', inquiryData.email);
            }

            // --- Footer ---
            const bottomY = 700;
            doc.moveTo(50, bottomY).lineTo(550, bottomY).strokeColor('#e2e8f0').stroke();

            doc.fontSize(10)
                .fillColor('#94a3b8')
                .text('This is an automated report generated by ASK Travels System.', 50, bottomY + 15, { align: 'center' });

            doc.text('© ' + new Date().getFullYear() + ' ASK Travels. All rights reserved.', 50, bottomY + 30, { align: 'center' });

            doc.end();

        } catch (error) {
            reject(error);
        }
    });
};

module.exports = { generateInquiryPDF };
